### PR TITLE
Support third party plugin install

### PR DESCRIPTION
**Pull request by holidayworking**
This PR is support `mkr plugin install`.

```
node['mackerel-agent']['extra_plugins'] = [
  {
    'name' => 'mackerelio/mackerel-plugin-aws-ecs',
    'version' => 'v0.0.4'
  }
]
```

### CODE REVIEW

**Review by astj — APPROVED** [review]

**Comment by astj** [comment]
[nit] p-r description does not follow https://github.com/mackerelio/itamae-plugin-recipe-mackerel-agent/pull/15/commits/c42291a93d883bd3c2cbf3c992d967074e9a625d yet. Can you update the description also?

**Comment by astj** [comment]
Thank you!

**Comment by holidayworking** [comment]
> [nit] p-r description does not follow c42291a yet. Can you update the description also?

I update the description.

**Comment by astj** [comment]
Released as v0.1.0.

**Pull request merged**
